name: Simple PHP Echo Pipeline

on:
  push:
    branches:
      - main

jobs:
  echo-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a PHP echo
        run: |
          echo "<?php echo 'Hello from GitHub Actions!'; ?>" > test.php
          php test.php
