name: Drupal 10 CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to Azure VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, iconv, intl, pdo, mysql

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Create artifact archive
        run: |
          mkdir artifact
          rsync -a --exclude='.git' --exclude='artifact' ./ artifact/
          tar -czf drupal-app.tar.gz -C artifact .

      - name: Copy archive to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: 22
          source: "drupal-app.tar.gz"
          target: "/var/www/html/AllTechHub"

      - name: SSH and deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf ${{ secrets.REMOTE_PATH }}/*
            sudo mkdir -p ${{ secrets.REMOTE_PATH }}
            sudo tar -xzf /tmp/drupal-app.tar.gz -C ${{ secrets.REMOTE_PATH }}
            sudo chown -R www-data:www-data ${{ secrets.REMOTE_PATH }}
            sudo chmod -R 755 ${{ secrets.REMOTE_PATH }}
            echo "Deployment completed!"