# .github/workflows/deploy.yml
trigger:
    branches:
      include:
        - main
  
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
    - script: echo "Pipeline triggered successfully!"
      displayName: 'Step 1: Initial Hello World'
  